// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gokeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login        *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_PasswordHash *string                `protobuf:"bytes,2,opt,name=passwordHash"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gokeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		if x.xxx_hidden_PasswordHash != nil {
			return *x.xxx_hidden_PasswordHash
		}
		return ""
	}
	return ""
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *User) SetPasswordHash(v string) {
	x.xxx_hidden_PasswordHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *User) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *User) HasPasswordHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *User) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *User) ClearPasswordHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PasswordHash = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login        *string
	PasswordHash *string
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.PasswordHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PasswordHash = b.PasswordHash
	}
	return m0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_gokeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EmptyMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EmptyMessage_builder) Build() *EmptyMessage {
	m0 := &EmptyMessage{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PasswordData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Pair        *string                `protobuf:"bytes,2,opt,name=pair"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,3,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PasswordData) Reset() {
	*x = PasswordData{}
	mi := &file_gokeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordData) ProtoMessage() {}

func (x *PasswordData) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PasswordData) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *PasswordData) GetPair() string {
	if x != nil {
		if x.xxx_hidden_Pair != nil {
			return *x.xxx_hidden_Pair
		}
		return ""
	}
	return ""
}

func (x *PasswordData) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *PasswordData) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *PasswordData) SetPair(v string) {
	x.xxx_hidden_Pair = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PasswordData) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PasswordData) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PasswordData) HasPair() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PasswordData) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PasswordData) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *PasswordData) ClearPair() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Pair = nil
}

func (x *PasswordData) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Metadata = nil
}

type PasswordData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Pair     *string
	Metadata *string
}

func (b0 PasswordData_builder) Build() *PasswordData {
	m0 := &PasswordData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Login = b.Login
	}
	if b.Pair != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Pair = b.Pair
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

type StatusResponce struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result      *string                `protobuf:"bytes,1,opt,name=result"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatusResponce) Reset() {
	*x = StatusResponce{}
	mi := &file_gokeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponce) ProtoMessage() {}

func (x *StatusResponce) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusResponce) GetResult() string {
	if x != nil {
		if x.xxx_hidden_Result != nil {
			return *x.xxx_hidden_Result
		}
		return ""
	}
	return ""
}

func (x *StatusResponce) SetResult(v string) {
	x.xxx_hidden_Result = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StatusResponce) HasResult() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StatusResponce) ClearResult() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Result = nil
}

type StatusResponce_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result *string
}

func (b0 StatusResponce_builder) Build() *StatusResponce {
	m0 := &StatusResponce{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Result != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Result = b.Result
	}
	return m0
}

var File_gokeeper_proto protoreflect.FileDescriptor

const file_gokeeper_proto_rawDesc = "" +
	"\n" +
	"\x0egokeeper.proto\x12\x19mrechkunov.goKeeper.proto\"@\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\"\n" +
	"\fpasswordHash\x18\x02 \x01(\tR\fpasswordHash\"\x0e\n" +
	"\fEmptyMessage\"T\n" +
	"\fPasswordData\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"(\n" +
	"\x0eStatusResponce\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x9b\x04\n" +
	"\bGoKeeper\x12X\n" +
	"\fRegisterUser\x12\x1f.mrechkunov.goKeeper.proto.User\x1a'.mrechkunov.goKeeper.proto.EmptyMessage\x12O\n" +
	"\vGetPassHash\x12\x1f.mrechkunov.goKeeper.proto.User\x1a\x1f.mrechkunov.goKeeper.proto.User\x12\\\n" +
	"\x10AuthenticateUser\x12\x1f.mrechkunov.goKeeper.proto.User\x1a'.mrechkunov.goKeeper.proto.EmptyMessage\x12L\n" +
	"\bEditUser\x12\x1f.mrechkunov.goKeeper.proto.User\x1a\x1f.mrechkunov.goKeeper.proto.User\x12V\n" +
	"\n" +
	"DeleteUser\x12\x1f.mrechkunov.goKeeper.proto.User\x1a'.mrechkunov.goKeeper.proto.EmptyMessage\x12`\n" +
	"\fSavePassword\x12'.mrechkunov.goKeeper.proto.PasswordData\x1a'.mrechkunov.goKeeper.proto.EmptyMessageB*Z(github.com/mrechkunov/goKeeper.git/protob\beditionsp\xe8\a"

var file_gokeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gokeeper_proto_goTypes = []any{
	(*User)(nil),           // 0: mrechkunov.goKeeper.proto.User
	(*EmptyMessage)(nil),   // 1: mrechkunov.goKeeper.proto.EmptyMessage
	(*PasswordData)(nil),   // 2: mrechkunov.goKeeper.proto.PasswordData
	(*StatusResponce)(nil), // 3: mrechkunov.goKeeper.proto.StatusResponce
}
var file_gokeeper_proto_depIdxs = []int32{
	0, // 0: mrechkunov.goKeeper.proto.GoKeeper.RegisterUser:input_type -> mrechkunov.goKeeper.proto.User
	0, // 1: mrechkunov.goKeeper.proto.GoKeeper.GetPassHash:input_type -> mrechkunov.goKeeper.proto.User
	0, // 2: mrechkunov.goKeeper.proto.GoKeeper.AuthenticateUser:input_type -> mrechkunov.goKeeper.proto.User
	0, // 3: mrechkunov.goKeeper.proto.GoKeeper.EditUser:input_type -> mrechkunov.goKeeper.proto.User
	0, // 4: mrechkunov.goKeeper.proto.GoKeeper.DeleteUser:input_type -> mrechkunov.goKeeper.proto.User
	2, // 5: mrechkunov.goKeeper.proto.GoKeeper.SavePassword:input_type -> mrechkunov.goKeeper.proto.PasswordData
	1, // 6: mrechkunov.goKeeper.proto.GoKeeper.RegisterUser:output_type -> mrechkunov.goKeeper.proto.EmptyMessage
	0, // 7: mrechkunov.goKeeper.proto.GoKeeper.GetPassHash:output_type -> mrechkunov.goKeeper.proto.User
	1, // 8: mrechkunov.goKeeper.proto.GoKeeper.AuthenticateUser:output_type -> mrechkunov.goKeeper.proto.EmptyMessage
	0, // 9: mrechkunov.goKeeper.proto.GoKeeper.EditUser:output_type -> mrechkunov.goKeeper.proto.User
	1, // 10: mrechkunov.goKeeper.proto.GoKeeper.DeleteUser:output_type -> mrechkunov.goKeeper.proto.EmptyMessage
	1, // 11: mrechkunov.goKeeper.proto.GoKeeper.SavePassword:output_type -> mrechkunov.goKeeper.proto.EmptyMessage
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gokeeper_proto_init() }
func file_gokeeper_proto_init() {
	if File_gokeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gokeeper_proto_rawDesc), len(file_gokeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gokeeper_proto_goTypes,
		DependencyIndexes: file_gokeeper_proto_depIdxs,
		MessageInfos:      file_gokeeper_proto_msgTypes,
	}.Build()
	File_gokeeper_proto = out.File
	file_gokeeper_proto_goTypes = nil
	file_gokeeper_proto_depIdxs = nil
}
