// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/gokeeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoKeeper_RegisterUser_FullMethodName     = "/mrechkunov.goKeeper.proto.GoKeeper/RegisterUser"
	GoKeeper_GetPassHash_FullMethodName      = "/mrechkunov.goKeeper.proto.GoKeeper/GetPassHash"
	GoKeeper_AuthenticateUser_FullMethodName = "/mrechkunov.goKeeper.proto.GoKeeper/AuthenticateUser"
	GoKeeper_EditUser_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/EditUser"
	GoKeeper_DeleteUser_FullMethodName       = "/mrechkunov.goKeeper.proto.GoKeeper/DeleteUser"
	GoKeeper_SavePassword_FullMethodName     = "/mrechkunov.goKeeper.proto.GoKeeper/SavePassword"
	GoKeeper_GetPass_FullMethodName          = "/mrechkunov.goKeeper.proto.GoKeeper/GetPass"
)

// GoKeeperClient is the client API for GoKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoKeeperClient interface {
	RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetPassHash(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	AuthenticateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	SavePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetPass(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*PasswordData, error)
}

type goKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGoKeeperClient(cc grpc.ClientConnInterface) GoKeeperClient {
	return &goKeeperClient{cc}
}

func (c *goKeeperClient) RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) GetPassHash(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GoKeeper_GetPassHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) AuthenticateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GoKeeper_EditUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) SavePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_SavePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) GetPass(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*PasswordData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordData)
	err := c.cc.Invoke(ctx, GoKeeper_GetPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoKeeperServer is the server API for GoKeeper service.
// All implementations must embed UnimplementedGoKeeperServer
// for forward compatibility.
type GoKeeperServer interface {
	RegisterUser(context.Context, *User) (*EmptyMessage, error)
	GetPassHash(context.Context, *User) (*User, error)
	AuthenticateUser(context.Context, *User) (*EmptyMessage, error)
	EditUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *User) (*EmptyMessage, error)
	SavePassword(context.Context, *PasswordData) (*EmptyMessage, error)
	GetPass(context.Context, *PasswordData) (*PasswordData, error)
	mustEmbedUnimplementedGoKeeperServer()
}

// UnimplementedGoKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoKeeperServer struct{}

func (UnimplementedGoKeeperServer) RegisterUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGoKeeperServer) GetPassHash(context.Context, *User) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPassHash not implemented")
}
func (UnimplementedGoKeeperServer) AuthenticateUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedGoKeeperServer) EditUser(context.Context, *User) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditUser not implemented")
}
func (UnimplementedGoKeeperServer) DeleteUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGoKeeperServer) SavePassword(context.Context, *PasswordData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePassword not implemented")
}
func (UnimplementedGoKeeperServer) GetPass(context.Context, *PasswordData) (*PasswordData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPass not implemented")
}
func (UnimplementedGoKeeperServer) mustEmbedUnimplementedGoKeeperServer() {}
func (UnimplementedGoKeeperServer) testEmbeddedByValue()                  {}

// UnsafeGoKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoKeeperServer will
// result in compilation errors.
type UnsafeGoKeeperServer interface {
	mustEmbedUnimplementedGoKeeperServer()
}

func RegisterGoKeeperServer(s grpc.ServiceRegistrar, srv GoKeeperServer) {
	// If the following call panics, it indicates UnimplementedGoKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoKeeper_ServiceDesc, srv)
}

func _GoKeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).RegisterUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_GetPassHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetPassHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetPassHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetPassHash(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).AuthenticateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_EditUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).EditUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_SavePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).SavePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_SavePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).SavePassword(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_GetPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetPass(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

// GoKeeper_ServiceDesc is the grpc.ServiceDesc for GoKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mrechkunov.goKeeper.proto.GoKeeper",
	HandlerType: (*GoKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _GoKeeper_RegisterUser_Handler,
		},
		{
			MethodName: "GetPassHash",
			Handler:    _GoKeeper_GetPassHash_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _GoKeeper_AuthenticateUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _GoKeeper_EditUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GoKeeper_DeleteUser_Handler,
		},
		{
			MethodName: "SavePassword",
			Handler:    _GoKeeper_SavePassword_Handler,
		},
		{
			MethodName: "GetPass",
			Handler:    _GoKeeper_GetPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gokeeper.proto",
}
