// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gokeeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoKeeper_GetPassHash_FullMethodName      = "/mrechkunov.goKeeper.proto.GoKeeper/GetPassHash"
	GoKeeper_RegisterUser_FullMethodName     = "/mrechkunov.goKeeper.proto.GoKeeper/RegisterUser"
	GoKeeper_AuthenticateUser_FullMethodName = "/mrechkunov.goKeeper.proto.GoKeeper/AuthenticateUser"
	GoKeeper_EditUser_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/EditUser"
	GoKeeper_DeleteUser_FullMethodName       = "/mrechkunov.goKeeper.proto.GoKeeper/DeleteUser"
	GoKeeper_SavePassword_FullMethodName     = "/mrechkunov.goKeeper.proto.GoKeeper/SavePassword"
	GoKeeper_GetPassword_FullMethodName      = "/mrechkunov.goKeeper.proto.GoKeeper/GetPassword"
	GoKeeper_EditPassword_FullMethodName     = "/mrechkunov.goKeeper.proto.GoKeeper/EditPassword"
	GoKeeper_DeletePassword_FullMethodName   = "/mrechkunov.goKeeper.proto.GoKeeper/DeletePassword"
	GoKeeper_SaveCard_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/SaveCard"
	GoKeeper_GetCard_FullMethodName          = "/mrechkunov.goKeeper.proto.GoKeeper/GetCard"
	GoKeeper_EditCard_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/EditCard"
	GoKeeper_DeleteCard_FullMethodName       = "/mrechkunov.goKeeper.proto.GoKeeper/DeleteCard"
	GoKeeper_SaveFile_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/SaveFile"
	GoKeeper_GetFile_FullMethodName          = "/mrechkunov.goKeeper.proto.GoKeeper/GetFile"
	GoKeeper_EditFile_FullMethodName         = "/mrechkunov.goKeeper.proto.GoKeeper/EditFile"
	GoKeeper_DeleteFile_FullMethodName       = "/mrechkunov.goKeeper.proto.GoKeeper/DeleteFile"
)

// GoKeeperClient is the client API for GoKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoKeeperClient interface {
	GetPassHash(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	AuthenticateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error)
	SavePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetPassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*PasswordData, error)
	EditPassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error)
	DeletePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error)
	SaveCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*CardData, error)
	EditCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error)
	DeleteCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error)
	SaveFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*FileData, error)
	EditFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error)
	DeleteFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type goKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGoKeeperClient(cc grpc.ClientConnInterface) GoKeeperClient {
	return &goKeeperClient{cc}
}

func (c *goKeeperClient) GetPassHash(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GoKeeper_GetPassHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) AuthenticateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GoKeeper_EditUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) SavePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_SavePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) GetPassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*PasswordData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordData)
	err := c.cc.Invoke(ctx, GoKeeper_GetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) EditPassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_EditPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) DeletePassword(ctx context.Context, in *PasswordData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_DeletePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) SaveCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_SaveCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) GetCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*CardData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardData)
	err := c.cc.Invoke(ctx, GoKeeper_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) EditCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_EditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) DeleteCard(ctx context.Context, in *CardData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_DeleteCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) SaveFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_SaveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) GetFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*FileData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileData)
	err := c.cc.Invoke(ctx, GoKeeper_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) EditFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_EditFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) DeleteFile(ctx context.Context, in *FileData, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, GoKeeper_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoKeeperServer is the server API for GoKeeper service.
// All implementations must embed UnimplementedGoKeeperServer
// for forward compatibility.
type GoKeeperServer interface {
	GetPassHash(context.Context, *User) (*User, error)
	RegisterUser(context.Context, *User) (*EmptyMessage, error)
	AuthenticateUser(context.Context, *User) (*EmptyMessage, error)
	EditUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *User) (*EmptyMessage, error)
	SavePassword(context.Context, *PasswordData) (*EmptyMessage, error)
	GetPassword(context.Context, *PasswordData) (*PasswordData, error)
	EditPassword(context.Context, *PasswordData) (*EmptyMessage, error)
	DeletePassword(context.Context, *PasswordData) (*EmptyMessage, error)
	SaveCard(context.Context, *CardData) (*EmptyMessage, error)
	GetCard(context.Context, *CardData) (*CardData, error)
	EditCard(context.Context, *CardData) (*EmptyMessage, error)
	DeleteCard(context.Context, *CardData) (*EmptyMessage, error)
	SaveFile(context.Context, *FileData) (*EmptyMessage, error)
	GetFile(context.Context, *FileData) (*FileData, error)
	EditFile(context.Context, *FileData) (*EmptyMessage, error)
	DeleteFile(context.Context, *FileData) (*EmptyMessage, error)
	mustEmbedUnimplementedGoKeeperServer()
}

// UnimplementedGoKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoKeeperServer struct{}

func (UnimplementedGoKeeperServer) GetPassHash(context.Context, *User) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPassHash not implemented")
}
func (UnimplementedGoKeeperServer) RegisterUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGoKeeperServer) AuthenticateUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedGoKeeperServer) EditUser(context.Context, *User) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method EditUser not implemented")
}
func (UnimplementedGoKeeperServer) DeleteUser(context.Context, *User) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGoKeeperServer) SavePassword(context.Context, *PasswordData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePassword not implemented")
}
func (UnimplementedGoKeeperServer) GetPassword(context.Context, *PasswordData) (*PasswordData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPassword not implemented")
}
func (UnimplementedGoKeeperServer) EditPassword(context.Context, *PasswordData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method EditPassword not implemented")
}
func (UnimplementedGoKeeperServer) DeletePassword(context.Context, *PasswordData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePassword not implemented")
}
func (UnimplementedGoKeeperServer) SaveCard(context.Context, *CardData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCard not implemented")
}
func (UnimplementedGoKeeperServer) GetCard(context.Context, *CardData) (*CardData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedGoKeeperServer) EditCard(context.Context, *CardData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method EditCard not implemented")
}
func (UnimplementedGoKeeperServer) DeleteCard(context.Context, *CardData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedGoKeeperServer) SaveFile(context.Context, *FileData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedGoKeeperServer) GetFile(context.Context, *FileData) (*FileData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedGoKeeperServer) EditFile(context.Context, *FileData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method EditFile not implemented")
}
func (UnimplementedGoKeeperServer) DeleteFile(context.Context, *FileData) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedGoKeeperServer) mustEmbedUnimplementedGoKeeperServer() {}
func (UnimplementedGoKeeperServer) testEmbeddedByValue()                  {}

// UnsafeGoKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoKeeperServer will
// result in compilation errors.
type UnsafeGoKeeperServer interface {
	mustEmbedUnimplementedGoKeeperServer()
}

func RegisterGoKeeperServer(s grpc.ServiceRegistrar, srv GoKeeperServer) {
	// If the following call panics, it indicates UnimplementedGoKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoKeeper_ServiceDesc, srv)
}

func _GoKeeper_GetPassHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetPassHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetPassHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetPassHash(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).RegisterUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).AuthenticateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_EditUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).EditUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_SavePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).SavePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_SavePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).SavePassword(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_GetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetPassword(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_EditPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).EditPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_EditPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).EditPassword(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_DeletePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).DeletePassword(ctx, req.(*PasswordData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_SaveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).SaveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_SaveCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).SaveCard(ctx, req.(*CardData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetCard(ctx, req.(*CardData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_EditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).EditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_EditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).EditCard(ctx, req.(*CardData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_DeleteCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).DeleteCard(ctx, req.(*CardData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_SaveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).SaveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_SaveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).SaveFile(ctx, req.(*FileData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).GetFile(ctx, req.(*FileData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_EditFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).EditFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_EditFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).EditFile(ctx, req.(*FileData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).DeleteFile(ctx, req.(*FileData))
	}
	return interceptor(ctx, in, info, handler)
}

// GoKeeper_ServiceDesc is the grpc.ServiceDesc for GoKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mrechkunov.goKeeper.proto.GoKeeper",
	HandlerType: (*GoKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPassHash",
			Handler:    _GoKeeper_GetPassHash_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _GoKeeper_RegisterUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _GoKeeper_AuthenticateUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _GoKeeper_EditUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GoKeeper_DeleteUser_Handler,
		},
		{
			MethodName: "SavePassword",
			Handler:    _GoKeeper_SavePassword_Handler,
		},
		{
			MethodName: "GetPassword",
			Handler:    _GoKeeper_GetPassword_Handler,
		},
		{
			MethodName: "EditPassword",
			Handler:    _GoKeeper_EditPassword_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _GoKeeper_DeletePassword_Handler,
		},
		{
			MethodName: "SaveCard",
			Handler:    _GoKeeper_SaveCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _GoKeeper_GetCard_Handler,
		},
		{
			MethodName: "EditCard",
			Handler:    _GoKeeper_EditCard_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _GoKeeper_DeleteCard_Handler,
		},
		{
			MethodName: "SaveFile",
			Handler:    _GoKeeper_SaveFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _GoKeeper_GetFile_Handler,
		},
		{
			MethodName: "EditFile",
			Handler:    _GoKeeper_EditFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _GoKeeper_DeleteFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gokeeper.proto",
}
